"use server";

export async function generateAiDraft(prompt: string, context: { leadName: string, planType: string }): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured.");
  }

  const systemInstruction = `You are a professional sales agent for CS Coworking Spaces. Write a short, friendly, and persuasive email/message draft.
Keep it under 3 paragraphs. End with "Cheers, CS Coworking Spaces".`;

  const userMessage = `Lead Name: ${context.leadName}\nInterested Plan: ${context.planType}\nPrompt/Instruction: ${prompt}\n\nPlease generate the message based on these details.`;

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          system_instruction: {
            parts: [{ text: systemInstruction }]
          },
          contents: [
            {
              parts: [{ text: userMessage }]
            }
          ]
        })
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API Error:", errorText);
      throw new Error(`Gemini API returned status ${response.status}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error("No text generated by Gemini.");
    }

    return generatedText.trim();
  } catch (error) {
    console.error("Failed to generate AI draft:", error);
    throw error;
  }
}
